### PR TITLE
New scene autoload

### PR DESCRIPTION
**Pull request by moxvallix**
Working PR for the new scene Autoload. Still to be documented.

### CODE REVIEW

**Comment by nicemicro** [comment]
OMG.
This should probably wait until the main is updated to have all the appearance related stuff, so the diff makes sense.

**Comment by moxvallix** [comment]
yeah don't review this until bertha is merged

**Comment by moxvallix** [comment]
it's just here so my work isn't going ahead without anyone knowing

**Comment by moxvallix** [comment]
Still do do:
- [ ] Comment the code properly
- [ ] Write documentation on the wiki

**Pull request merged**
