### PR TITLE
Lobby map is a moving train now.

### LINKED ISSUE #40: Re-implement the lobby map
The lobby should be the moving train.

### PR DESCRIPTION
**Pull request by nicemicro**
Imported and adapted J. Ngo's previous lobby map into this one.

Should close #40

### CODE REVIEW

**Review by TheSecondReal0 — DISMISSED** [review]
Bottom wall fade in/out doesn't work, aside from that everything looks good!

**Review by TheSecondReal0 — CHANGES_REQUESTED** [review]
Bottom wall fade in/out doesn't work, aside from that everything looks good!

**Review by TheSecondReal0 — DISMISSED** [review]
Looks good!

**Review by monban — DISMISSED** [review]
I like the new camera!

**Review by monban — DISMISSED** [review]

**Review by monban — APPROVED** [review]

**Pull request merged**
