### PR TITLE
Added character customisation menu, and icons

### PR DESCRIPTION
**Pull request by moxvallix**

### CODE REVIEW

**Review by nicemicro — COMMENTED** [review]
1. appearance.gd at line 96 for function _colorFromMapXY misses the type definitions for parameters.
2. appearance_editor.gd seems to miss all type definitions for parameters in all functions.
3. skeleton.gd misses type definitions for function _applyColors at line 53.
4. mainmenu.gd on line 114, I think the use of signal there is not really warranted, looks like an avoidable situation, similarly, with appearance_editor.gd line 115. These would be better served with regular function calls, IMHO.

I don't think any of these must be resolved for merging this in, as this is a feature branch, so if you don't feel like / don't have time to implement, we can just merge these in, and let others work on it too.

**Comment by nicemicro** [comment]
* in the skeleton.tscn, all of the sprites are scaled down 0.05; 
* then they are blown up 8x in menu_player.tscn
* and 2x in the appearance_editor.tscn

**Comment by moxvallix** [comment]
> * in the skeleton.tscn, all of the sprites are scaled down 0.05;
> 
>     * then they are blown up 8x in menu_player.tscn
> 
>     * and 2x in the appearance_editor.tscn

Hmm that must be left over from the old game, did not notice that. I will make all sprites in skeleton.tcsn 100% scaled

**Comment by moxvallix** [comment]
I haven't touched skeleton.tscn, but that is because I don't really know the best way of doing that. I would like someone else to look in to that, if that is ok. Leave that to a different PR, this one is already insanely large.

**Review by nicemicro — APPROVED** [review]
Let's do it.

**Pull request merged**
