### PR TITLE
Item sprites added

### PR DESCRIPTION
**Pull request by nicemicro**

### CODE REVIEW

**Comment by moxvallix** [comment]
Please merge main into this branch, as to clean up the diff.

**Comment by nicemicro** [comment]
> Please merge main into this branch, as to clean up the diff.

This PR does that. Besides that, it places a few sprites here and there.

**Review by TheSecondReal0 — CHANGES_REQUESTED** [review]
Looks good, just need to rename the ingame-texture file to follow the naming convention by switching the dash to an underscore. I'd also make it plural, so ingame_textures

**Comment by moxvallix** [comment]
> Looks good, just need to rename the ingame-texture file to follow the naming convention by switching the dash to an underscore. I'd also make it plural, so ingame_textures

Most other places we have just been calling the textures folder textures, so maybe it should even be called that.

**Comment by nicemicro** [comment]
> Most other places we have just been calling the textures folder textures, so maybe it should even be called that.

In the item case, I'd have separate folder for the textures that appear on the map / in the hands of players and the textures that would appear on the item while it is in a task (maybe a bigger one?)

**Pull request merged**
