### PR TITLE
Task system

### PR DESCRIPTION
**Pull request by nicemicro**
Task system implemented with a chemical cabinet.
Tasks are handled by a node attached to the map, and the tasks has to be attached directly under this node.
Task state is stored by resources attached to the task scenes.
Task states are synced through the network.
Items can spawn in tasks, and can be picked out of tasks.

### CODE REVIEW

**Comment by nicemicro** [comment]
Contains everything and more as outlined in #39, therefore it should close #39.

**Comment by vincens2005** [comment]
It appears to work. My only critique is that the cabinet handles are extremely hard to interact with, but the task sync seems solid.

**Review by vincens2005 — APPROVED** [review]

**Comment by vincens2005** [comment]
Actually, the task state seems to reset every minute or so, even if someone has it open

**Comment by nicemicro** [comment]
@vincens2005 yeah, the handles of the cabinet (specifically the right hand one) is something I couldn't figure out why it is so hard to handle, might be something under the task window taking the cursor focus away, and not triggering the mouse event properly.

The reset of the cabinet door in 7 seconds is intentional, I was trying to simulate the kind of spring mechanism that often closes these types of doors.

**Pull request merged**
